---

# read tls certificate and key from source secret
# create tls certificate for amq streams

- name: "Get tls secret with certificates for Kafka broker"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ amq_streams_tls_source_secret_namespace }}"
    name: "{{ amq_streams_tls_source_secret }}"
  register: r_amq_streams_source_tls_secret

- name: "Get certificate and private key"
  ansible.builtin.set_fact:
    amq_streams_tls_certificate: "{{ r_amq_streams_source_tls_secret | json_query('resources[0].data.\"tls.crt\"') }}"
    amq_streams_tls_private_key: "{{ r_amq_streams_source_tls_secret | json_query('resources[0].data.\"tls.key\"') }}"

- name: "Create TLS Secret for AMQ Streams"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ cdc_poc_namespace }}"
    definition: "{{ lookup('template', resource) | from_yaml }}"
  vars:
    resource: "templates/amq-streams-tls-secret.j2"
